In [1]:
import pandas as pd

In [22]:
df=pd.read_csv('data2.csv')
##Fetch first 5 rows
df.head(5)

,conceptType,conceptUri,preferredLabel,altLabels,hiddenLabels,status,modifiedDate,scopeNote,inScheme,description,code
0,SkillGroup,http://data.europa.eu/esco/isced-f/00,generic programmes and qualifications,NaN,NaN,released,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Generic programmes and qualifications are thos...,NaN
1,SkillGroup,http://data.europa.eu/esco/isced-f/000,generic programmes and qualifications not furt...,NaN,NaN,released,2023-07-13T15:16:44.968Z,NaN,http://data.europa.eu/esco/concept-scheme/skil...,NaN,NaN
2,SkillGroup,http://data.europa.eu/esco/isced-f/0000,generic programmes and qualifications not furt...,NaN,NaN,released,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,NaN,NaN
3,SkillGroup,http://data.europa.eu/esco/isced-f/001,basic programmes and qualifications,NaN,NaN,released,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,NaN,1
4,SkillGroup,http://data.europa.eu/esco/isced-f/0011,basic programmes and qualifications,NaN,NaN,released,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Basic programmes and qualifications are design...,11

In [23]:
df.describe()

,conceptType,conceptUri,preferredLabel,altLabels,hiddenLabels,status,modifiedDate,scopeNote,inScheme,description,code
count,640,640,640,112,17,636,339,324,640,507,637
unique,1,640,518,70,17,1,319,281,3,425,627
top,SkillGroup,http://data.europa.eu/esco/skill/f5328159-dfe9...,"communication, collaboration and creativity",working with information,professional orientation and perfection\ndemon...,released,2022-06-19T15:45:14.266Z,Excludes:\n- Specific skills involving interac...,http://data.europa.eu/esco/concept-scheme/skil...,"Collecting, storing, monitoring, and using inf...",99
freq,640,1,3,3,1,636,13,3,390,3,3

In [24]:
##Handling missing values 
df.isnull().any(axis=1)

0      True
1      True
2      True
3      True
4      True
       ...
635    True
636    True
637    True
638    True
639    True
Length: 640, dtype: bool

In [15]:
df.isnull().sum()

Student_ID                    0
Major_Category                0
Year_of_Study                 0
Pre_Semester_GPA              0
Weekly_GenAI_Hours            0
Primary_Use_Case              0
Prompt_Engineering_Skill      0
Tool_Diversity                0
Paid_Subscription             0
Traditional_Study_Hours       0
Perceived_AI_Dependency       0
Institutional_Policy          0
Anxiety_Level_During_Exams    0
Post_Semester_GPA             0
Skill_Retention_Score         0
Burnout_Risk_Level            0
dtype: int64

In [25]:
df_fillna=df.fillna(0)

In [26]:
##Filling missing value with the mean of the cloumn
##For sales report the Sales column has missing values which are replaced by the mean 
##df['Sales_fillna']=df['Sales'].fillna(df['Sales'].mean())

In [27]:
df.dtypes

conceptType       object
conceptUri        object
preferredLabel    object
altLabels         object
hiddenLabels      object
status            object
modifiedDate      object
scopeNote         object
inScheme          object
description       object
code              object
dtype: object

In [30]:
##Renaming columns
df.rename(columns={'conceptType':'conceptTypes'})

,conceptTypes,conceptUri,preferredLabel,altLabels,hiddenLabels,status,modifiedDate,scopeNote,inScheme,description,code
0,SkillGroup,http://data.europa.eu/esco/isced-f/00,generic programmes and qualifications,NaN,NaN,released,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Generic programmes and qualifications are thos...,NaN
1,SkillGroup,http://data.europa.eu/esco/isced-f/000,generic programmes and qualifications not furt...,NaN,NaN,released,2023-07-13T15:16:44.968Z,NaN,http://data.europa.eu/esco/concept-scheme/skil...,NaN,NaN
2,SkillGroup,http://data.europa.eu/esco/isced-f/0000,generic programmes and qualifications not furt...,NaN,NaN,released,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,NaN,NaN
3,SkillGroup,http://data.europa.eu/esco/isced-f/001,basic programmes and qualifications,NaN,NaN,released,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,NaN,1
4,SkillGroup,http://data.europa.eu/esco/isced-f/0011,basic programmes and qualifications,NaN,NaN,released,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Basic programmes and qualifications are design...,11
...,...,...,...,...,...,...,...,...,...,...,...
635,SkillGroup,http://data.europa.eu/esco/skill/fbb861f7-2386...,providing personal care,personal care,NaN,released,NaN,Excludes:\n- Administration of medical treatme...,http://data.europa.eu/esco/concept-scheme/skil...,Responding to the daily and occasional persona...,S3.6.0
636,SkillGroup,http://data.europa.eu/esco/skill/fe317a4c-e4e0...,protecting and enforcing,NaN,NaN,released,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Responding to public and personal safety and s...,S3.3.0
637,SkillGroup,http://data.europa.eu/esco/skill/fe5eabaa-63f6...,leading others,demonstrating leadership,leadership,released,2021-08-30T16:33:15.592Z,NaN,http://data.europa.eu/esco/concept-scheme/skil...,"Guide, direct and motivate others.",T4.4
638,SkillGroup,http://data.europa.eu/esco/skill/ff565308-8f29...,handling and moving,handling goods or animals,NaN,released,NaN,Excludes:\n- Specific skills involving interac...,http://data.europa.eu/esco/concept-scheme/skil...,"Sorting, arranging, moving, transforming, fabr...",S6.0
639,SkillGroup,http://data.europa.eu/esco/skill/fff1d675-c36a...,"processing information, ideas and concepts",processing of information\nprocessing qualitat...,using knowledge and information,released,2021-08-30T13:39:50.945Z,NaN,http://data.europa.eu/esco/concept-scheme/skil...,"Evaluate, input, record, transcribe and update...",T2.1

In [31]:
##Chnage the datatype
##df[new_column_name']=df['column_name'].astype(the datatype in which we want to convert)

In [32]:
## Data Aggregating and grouping
##grouped_mean=df.groupby('column_name')['column_name_1'].mean() groupby one column and aggregate from same column or diff
##grouped_sum=df.groupby('column_name',column_name2)['column_name_1'].sum() groupby two column and aggregate from same column or diff
##grouped_agg=df.groupby('column_name',column_name2)['column_name_1'].agg['mean','sum','count'] groupby one column and use all aggregate function for the same column or diff

In [41]:
##Merging and joining the dataframes 
df1=pd.DataFrame({'Key':['A','B','C'], 'Values':[1,2,3]})
df2=pd.DataFrame({'Key':['A','B','D'], 'Values':[4,5,6]})

In [42]:
df1

  Key  Values
0   A       1
1   B       2
2   C       3

In [43]:
df2

  Key  Values
0   A       4
1   B       5
2   D       6

In [44]:
##Merge the Dataframe on the key column
pd.merge(df1,df2,on='Key',how='inner')

  Key  Values_x  Values_y
0   A         1         4
1   B         2         5

In [45]:
pd.merge(df1,df2,on='Key',how='outer')

  Key  Values_x  Values_y
0   A       1.0       4.0
1   B       2.0       5.0
2   C       3.0       NaN
3   D       NaN       6.0

In [46]:
pd.merge(df1,df2,on='Key',how='left')

  Key  Values_x  Values_y
0   A         1       4.0
1   B         2       5.0
2   C         3       NaN

In [47]:
pd.merge(df1,df2,on='Key',how='right')

  Key  Values_x  Values_y
0   A       1.0         4
1   B       2.0         5
2   D       NaN         6